import { NextResponse } from 'next/server';
import { writeFileSync, existsSync } from 'fs';
import { join } from 'path';

// Force dynamic rendering (uses file system)
export const dynamic = 'force-dynamic';

export async function POST(request) {
  try {
    const { jwtSecret, pokemonApiKey } = await request.json();

    const envPath = join(process.cwd(), '.env');
    
    // Check if already exists
    if (existsSync(envPath)) {
      return NextResponse.json({
        error: '.env already exists. Delete it first if you want to reinstall.'
      }, { status: 400 });
    }

    // Create .env content
    const envContent = `# trace.cards Environment Configuration
# Generated by installer on ${new Date().toISOString()}

DATABASE_URL="file:./data/production.db"
JWT_SECRET="${jwtSecret}"
NODE_ENV="production"
${pokemonApiKey ? `POKEMON_API_KEY="${pokemonApiKey}"` : '# POKEMON_API_KEY="" # Add your Pokemon TCG API key here'}
`;

    // Write .env file
    writeFileSync(envPath, envContent, 'utf8');

    return NextResponse.json({
      success: true,
      message: 'Environment configured successfully'
    });

  } catch (error) {
    console.error('Setup env error:', error);
    return NextResponse.json({
      error: error.message
    }, { status: 500 });
  }
}
